service: layers-Recetas
# frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: us-east-1
  

layers:
  CommonModelsDb:
    path: layersCommonModelsDb

functions:
  hello:
    handler: handler.hello
